### ISSUE TITLE
Publish 3.0.0 to npm

### ISSUE THREAD

**Issue by yono38** [iamraphson/react-ravepayment#24]
Hey - thanks for making this, super helpful for quickly pulling in Flutterwave to my app!

Small request - I'm using typescript and saw that you've merged a PR that includes type definitions but the current published version (2.0.8) on NPMJS doesn't include that yet. Would you mind publishing the newer 3.0.0 version please?

Thanks!

**Comment by iamraphson** [comment]
@yono38 done. https://www.npmjs.com/package/react-ravepayment
