### ISSUE TITLE
Invalid public key passed

### ISSUE THREAD

**Issue by dinorhythms** [iamraphson/react-ravepayment#28]
Am getting Invalid public key passed in the flutterwave popup

**Comment by iamraphson** [comment]
@dinorhythms can you share your sample code?

**Comment by Quadriphobs1** [comment]
@dinorhythms Are you passing the `production: true` when you are in production

**Comment by dinorhythms** [comment]
@iamraphson @Quadriphobs1 yes i did passed production: true. I sorted it using flutterwave script directly. Sorry for the delay in response. Thanks
