### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by alfredasare** [iamraphson/react-ravepayment#31]
After a successful payment, I keep seeing this error in the console 

scripts.min.js:1 Uncaught TypeError: Cannot set property 'textContent' of null
    at scripts.min.js:1

The bad thing is that it keeps console logging the same error as long as the site is open

![Screenshot (27)](https://user-images.githubusercontent.com/38125880/79574900-6a0c1e80-80b0-11ea-859e-780e38485d1c.png)

**Comment by iamraphson** [comment]
still having the issue?

**Comment by alfredasare** [comment]
I have not tried in a while. I'll let you know immediately after I'm done
checking

**Comment by alfredasare** [comment]
yeah still having the issue

**Comment by iamraphson** [comment]
@alfredasare send your sample code.

**Comment by alfredasare** [comment]
Here's a snippet


`const [flutterWaveKeys, setKeys] = useState({});

    useEffect(() => {
        const keysRequest = functions.httpsCallable('flutterwave');
        keysRequest()
            .then((result) => {
                setKeys(result.data);
            })
            .catch((error) => {
                console.log(error);
            });
    }, []);

    const [billingInfo, setBillingInfo] = useState({
        cycle: '',
        pay: '',
        error: '',
        amount: 0,
        subscription_type: ''
    });

    const myDate = [];
    const date = new Date();
    myDate.push(date.getDate());
    myDate.push(date.getMonth() + 1);
    myDate.push(date.getFullYear());
    const renewalDate = myDate.join('-');
    const lastDatePaid = date.toString();

    const setBillingCycle = (event) => {
        if (event.target.value === 'annual') {
            setBillingInfo({
                ...billingInfo,
                cycle: 'Annual',
                pay: 'Ghana cedis 100',
                amount: 100,
                subscription_type: 'annual',
                error: '',
            });
        } else if (event.target.value === 'six_months') {
            setBillingInfo({
                ...billingInfo,
                cycle: 'Six(6) months',
                pay: 'Ghana cedis 40',
                amount: 40,
                subscription_type: 'six_months',
                error: '',
            });
        } else if (event.target.value === 'three_months') {
            setBillingInfo({
                ...billingInfo,
                cycle: 'Three(3) months',
                pay: 'Ghana cedis 20',
                amount: 20,
                subscription_type: 'three_months',
                error: '',
            });
        }
    };

    const config = {
        txref: "MC-" + Date.now(),
        customer_firstname: property.username,
        customer_email: property.email,
        customer_phone: property.contact,
        amount: billingInfo.amount,
        PBFPubKey: flutterWaveKeys.publicKey,
        currency: "GHS",
        country: "GH",
        production: false,
    };


    const {initializePayment} = useRavePayment(config);

    const onPaymentSuccess = () => {
        const {subscription_type} = billingInfo;
        updatePaymentData({property, lastDatePaid, subscription_type});
        history.push(`/dashboard`);
    };

    const onModalClose = () => {
        // console.log("Modal closed")
    };

    const handlePayment = event => {
        let isValid;
        event.preventDefault();
        if (billingInfo.cycle === '') {
            setBillingInfo({...billingInfo, error: 'Please choose a billing cycle'});
            isValid = false;
        } else {
            isValid = true;
        }
        isValid ? initializePayment(onPaymentSuccess, onModalClose) : console.log();
    };`
